# action.yml
name: "Update SPEC 0 dependencies"
description: "Update the lower bounds of Python dependencies covered by the Scientific Python SPEC 0 support schedule"
author: Scientific Python Developers

inputs:
  target_branch:
    description: "Target branch for the pull request"
    required: true
    default: "main"
  project_file_name:
    description: "Path to the project file listing dependencies, relative to repository root. Defaults to 'pyproject.toml'. Currently only pyproject.toml is supported."
    required: true
    default: "pyproject.toml"
  create_pr:
    description: "Whether the action should open a PR or not. Set to false for dry-run/testing."
    required: true
    default: true
  commit_msg:
    description: "Commit message for the commit to update the versions. by default 'Drop support for unsupported packages conform SPEC 0'. has no effect if `create_pr` is set to false"
    required: false
    default: "chore: Drop support for unsupported packages conform SPEC 0"
  pr_title:
    description: "The title of the PR that will be opened. by default 'Drop support for unsupported packages conform SPEC 0'. has no effect if `create_pr` is set to false"
    required: false
    default: "chore: Drop support for unsupported packages conform SPEC 0"
  schedule_path:
    description: "Path to the schedule.json file relative to the project root. If missing, it will be downloaded from the latest release of savente93/SPEC0-schedule"
    default: "schedule.json"
  token:
    description: "GitHub token with repo permissions to create pull requests"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Set up Git
      shell: bash
      run: |
        git config user.name "Scientific Python [bot]"
        git config user.email "scientific-python@users.noreply.github.com"
    - uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
      name: Setup Pixi
      with:
        pixi-version: v0.49.0
        manifest-path: ${{ github.action_path }}/pyproject.toml
    - name: Fetch Schedule from release
      uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
      with:
        repository: "savente93/SPEC0-schedule"
        latest: true
        fileName: "schedule.json"
    - name: Run update script
      shell: bash
      run: |
        set -e
        echo "Updating ${{ inputs.project_file_name }} using schedule ${{ inputs.schedule_path }}"
        pixi run --manifest-path ${{ github.action_path }}/pyproject.toml update-dependencies "${{ github.workspace }}/${{ inputs.project_file_name }}" "${{ github.workspace }}/${{ inputs.schedule_path }}"
    - name: Changes
      id: changes
      shell: bash
      run: |
        echo "Showing changes that would be committed"
        git --no-pager diff ${{ inputs.project_file_name }}
        if git diff --quiet ${{ inputs.project_file_name }}; then
          echo "changes_detected=false" >> "$GITHUB_OUTPUT"
        else
          echo "changes_detected=true"  >> "$GITHUB_OUTPUT"
        fi
    - name: Create Pull Request
      if: ${{ fromJSON(inputs.create_pr) && fromJSON(steps.changes.outputs.changes_detected) }}
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
      with:
        token: ${{ inputs.token }}
        commit-message: ${{ inputs.commit_msg }}
        title: ${{ inputs.pr_title }}
        body: "This PR was created automatically"
        base: ${{ inputs.target_branch }}
        branch: update-spec0-dependencies-${{ github.run_id }}
        add-paths: |
          ${{ inputs.project_file_name }}

branding:
  icon: "check-square"
  color: "blue"
