name: Run the update test suite
on:
  push:
    branches:
      - "main"
      - "*.*"
    tags:
      - "v*"
  pull_request:
  # Allow manual runs through the web UI
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          pixi-version: "v0.69.0"
      - run: |
          pixi run test
