name: Run the update test suite
on:
  push:
    branches:
      - "main"
      - "*.*"
    tags:
      - "v*"
  pull_request:
  # Allow manual runs through the web UI
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          pixi-version: "v0.69.0"
      - run: |
          pixi run test
